"""Second migration

Revision ID: 0b9554075447
Revises: 51be5f51b742
Create Date: 2023-07-24 18:09:40.730708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9554075447'
down_revision = '51be5f51b742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
