"""Add user model

Revision ID: 51be5f51b742
Revises: c2378b70e093
Create Date: 2023-07-23 16:14:14.359157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51be5f51b742'
down_revision = 'c2378b70e093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
